global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "flink-jobmanager"
    static_configs:
      - targets: ["flink-jobmanager:9249"]
    metrics_path: /

  - job_name: "flink-taskmanager"
    static_configs:
      - targets: ["datakata-flink-taskmanager-1:9249", "datakata-flink-taskmanager-2:9249"]
    metrics_path: /

  - job_name: "clickhouse"
    static_configs:
      - targets: ["clickhouse:8123"]
    metrics_path: /metrics

  - job_name: "results-api"
    static_configs:
      - targets: ["results-api:8080"]
    metrics_path: /actuator/prometheus
